### PR TITLE
Use stringstream instead of stod to work around locale issues.

### LINKED ISSUE #41: Parsing floats in URDF yields wrong value depending on locale
`urdfdom_headers` uses `std::stod` to parse floating point values like position (xyz) and rotation (rpy) from URDF files. The result of `std::stod` is locale dependant. So with e.g. a German locale (de_DE.UTF-8) "1.57079632679" is parsed to `1`.
This is the case in  `urdfdom_headers/urdf_model/include/urdf_model/pose.h` Line 70 (not necessarily exclusive)

In my opinion the issue described [here](https://github.com/ros-visualization/rviz/issues/1151) can be linked to this error, as can be the issue described [here](https://github.com/ros-planning/moveit/issues/690).

[This link](https://www.reddit.com/r/cpp/comments/2e68nd/stdstod_is_locale_dependant_but_the_docs_does_not/) states that "[...] using a stringstream to convert it worked perfectly fine."

If desired I can fix this issue using stringstream and create a pull request, but I have to admit I have no background knowledge in ros package building and testing procedures.

Cheers

### PR DESCRIPTION
**Pull request by clalancette**
The URDF schema (https://github.com/ros/urdfdom/blob/master/xsd/urdf.xsd#L47) defines doubles in URDF as xs:double. Looking at the XSD document at https://www.w3.org/TR/xmlschema-2/#double, it says that the mantissa for a double is represented as a "decimal" number. And looking at the XSD document at https://www.w3.org/TR/xmlschema-2/#decimal, a decimal number is a "finite-length sequence of decimal digits (#x30-#x39) separated by a period as a decimal indicator". Thus, the locale should have no effect on how the document is parsed, and using std::stod is incorrect.  This patch switches the Vector3 class to using the stream operator, which seems to ignore locale.

fixes #41 

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by traversaro** [comment]
>  This patch switches the Vector3 class to using the stream operator, which seems to ignore locale.

If I understood correctly the C++ documentation, the `stringstream` default locale is not affected by calls to the C-style [`std::setlocale`](http://en.cppreference.com/w/cpp/locale/setlocale) function (the one called by Qt, that is actually exposing the `std::stod` problem). However, it is affected by calls to [`std::locale::global`](http://en.cppreference.com/w/cpp/locale/locale/global), so a call to this `global` function in any part of the thread or the process (this is implementation defined) could still cause a failure in the URDF parser. Adding a call to the imbue method: 
~~~
ss.imbue(std::locale::classic());
~~~
should avoid this problem (see https://github.com/robotology/idyntree/issues/288#issuecomment-299447873).

**Comment by clalancette** [comment]
> Adding a call to the imbue method:

Thanks for that.  Done in 678ab93

**Comment by gavanderhoorn** [comment]
@clalancette: minor, but none of the three commits seem to have been made using your gh registered email, so they are not attributed to your account.

**Comment by clalancette** [comment]
> @clalancette: minor, but none of the three commits seem to have been made using your gh registered email, so they are not attributed to your account.

Ah, thanks.  When we got the new "@openrobotics.org" domain, I updated my .gitconfig, but I had forgotten to verify with GitHub.  Done now.

File: urdf_model/include/urdf_model/utils.h [hunk 1]
```diff
@@ -62,6 +62,28 @@ void split_string(std::vector<std::string> &result,
...
 }
 
+// This is a locale-safe version of string-to-double, which is suprisingly
+// difficult to do correctly.  This function ensures that the C locale is used
+// for parsing, as that matches up with what the XSD for double specifies.
+// On success, the double is returned; on failure, a std::runtime_error is
+// thrown.
+static inline double strToDouble(const char *in)
+{
+  std::stringstream ss;
```
Comment (sloretz) [inline urdf_model/include/urdf_model/utils.h]: `#include <sstream>`?

File: urdf_model/include/urdf_model/utils.h [hunk 2]
```diff
@@ -62,6 +62,28 @@ void split_string(std::vector<std::string> &result,
...
+  ss.imbue(std::locale::classic());
```
Comment (sloretz) [inline urdf_model/include/urdf_model/utils.h]: `#include <locale>`?

File: urdf_model/include/urdf_model/utils.h [hunk 3]
```diff
@@ -62,6 +62,28 @@ void split_string(std::vector<std::string> &result,
...
+
+  ss << in;
+
+  double out;
+  ss >> out;
+
+  if (ss.fail() || !ss.eof()) {
+    throw std::runtime_error("");
```
Comment (sloretz) [inline urdf_model/include/urdf_model/utils.h]: `#include <stdexcept>` ?

**Comment by clalancette** [comment]
I've fixed up all of the includes in caf2e8c.  As far as testing goes, the only thing is that there is no test infrastructure in here.  I could see about adding it (gtest or similar), but then this will grow into a much larger PR.  I'm inclined to kick that to another PR, but I'll let you make the final decision.

**Comment by traversaro** [comment]
>  As far as testing goes, the only thing is that there is no test infrastructure in here. I could see about adding it (gtest or similar), but then this will grow into a much larger PR. I'm inclined to kick that to another PR, but I'll let you make the final decision.

I am totally not a fan of the situation, but historically tests of `urdfdom_headers` were added in the urdfdom repo, see https://github.com/ros/urdfdom/pull/67#issuecomment-163352725 .

**Comment by clalancette** [comment]
@traversaro Thanks a lot for the pointer.  I'll go ahead and add some tests over there.

**Comment by clalancette** [comment]
@scpeters Gentle ping; this PR (and the related ros/urdfdom#109) are ready for review and merging, and I'd like to get them in before Melodic.  Thanks!

File: urdf_model/include/urdf_model/utils.h [hunk 4]
```diff
@@ -62,6 +65,28 @@ void split_string(std::vector<std::string> &result,
   }
 }
 
+// This is a locale-safe version of string-to-double, which is suprisingly
+// difficult to do correctly.  This function ensures that the C locale is used
+// for parsing, as that matches up with what the XSD for double specifies.
+// On success, the double is returned; on failure, a std::runtime_error is
+// thrown.
+static inline double strToDouble(const char *in)
```
Comment (scpeters) [inline urdf_model/include/urdf_model/utils.h]: Why use `const char *` instead of `const std::string &`? Just curious, not asking you to change it, just hoping to learn something.

Comment (clalancette) [reply urdf_model/include/urdf_model/utils.h]: There is a good (but sneaky) reason for it.  I'm hoping that once we get this basic support in, we can use this more generally throughout the urdfdom libraries to avoid this problem.  As one example, https://github.com/ros/urdfdom/blob/master/urdf_parser/src/link.cpp#L120 probably suffers from a similar problem (as do several other std::stod conversions in there).  Several of those get a `const char *` from tinyxml, so I figured this interface was more generic rather than having to wrap those inside strings.

Comment (clalancette) [reply urdf_model/include/urdf_model/utils.h]: Oh, right, I forgot I also did another PR to actually fix all of that as well: https://github.com/ros/urdfdom/pull/105
